// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieStore_API.Data;

#nullable disable

namespace MovieStore_API.Migrations
{
    [DbContext(typeof(MovieStoreDbContext))]
    [Migration("20240504103046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CartProduct", b =>
                {
                    b.Property<int>("CartsCartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.HasKey("CartsCartId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("CartProduct", (string)null);
                });

            modelBuilder.Entity("MovieStore_API.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);

                    b.HasData(
                        new
                        {
                            CartId = 1,
                            UserId = 1
                        },
                        new
                        {
                            CartId = 2,
                            UserId = 2
                        },
                        new
                        {
                            CartId = 3,
                            UserId = 3
                        },
                        new
                        {
                            CartId = 4,
                            UserId = 4
                        },
                        new
                        {
                            CartId = 5,
                            UserId = 5
                        },
                        new
                        {
                            CartId = 6,
                            UserId = 6
                        },
                        new
                        {
                            CartId = 7,
                            UserId = 7
                        },
                        new
                        {
                            CartId = 8,
                            UserId = 8
                        },
                        new
                        {
                            CartId = 9,
                            UserId = 9
                        },
                        new
                        {
                            CartId = 10,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("MovieStore_API.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductID");

                    b.ToTable("Items", (string)null);

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            CartId = 1,
                            ProductID = 1,
                            Quantity = 2
                        },
                        new
                        {
                            ItemID = 2,
                            CartId = 2,
                            ProductID = 3,
                            Quantity = 1
                        },
                        new
                        {
                            ItemID = 3,
                            CartId = 3,
                            ProductID = 5,
                            Quantity = 3
                        },
                        new
                        {
                            ItemID = 4,
                            CartId = 4,
                            ProductID = 7,
                            Quantity = 2
                        },
                        new
                        {
                            ItemID = 5,
                            CartId = 5,
                            ProductID = 9,
                            Quantity = 1
                        },
                        new
                        {
                            ItemID = 6,
                            CartId = 6,
                            ProductID = 11,
                            Quantity = 4
                        },
                        new
                        {
                            ItemID = 7,
                            CartId = 7,
                            ProductID = 13,
                            Quantity = 2
                        },
                        new
                        {
                            ItemID = 8,
                            CartId = 8,
                            ProductID = 15,
                            Quantity = 3
                        },
                        new
                        {
                            ItemID = 9,
                            CartId = 9,
                            ProductID = 17,
                            Quantity = 1
                        },
                        new
                        {
                            ItemID = 10,
                            CartId = 10,
                            ProductID = 19,
                            Quantity = 5
                        },
                        new
                        {
                            ItemID = 11,
                            CartId = 1,
                            ProductID = 2,
                            Quantity = 1
                        },
                        new
                        {
                            ItemID = 12,
                            CartId = 2,
                            ProductID = 4,
                            Quantity = 2
                        },
                        new
                        {
                            ItemID = 13,
                            CartId = 3,
                            ProductID = 6,
                            Quantity = 1
                        },
                        new
                        {
                            ItemID = 14,
                            CartId = 4,
                            ProductID = 8,
                            Quantity = 3
                        },
                        new
                        {
                            ItemID = 15,
                            CartId = 5,
                            ProductID = 10,
                            Quantity = 2
                        },
                        new
                        {
                            ItemID = 16,
                            CartId = 6,
                            ProductID = 12,
                            Quantity = 4
                        },
                        new
                        {
                            ItemID = 17,
                            CartId = 7,
                            ProductID = 14,
                            Quantity = 1
                        },
                        new
                        {
                            ItemID = 18,
                            CartId = 8,
                            ProductID = 16,
                            Quantity = 2
                        },
                        new
                        {
                            ItemID = 19,
                            CartId = 9,
                            ProductID = 18,
                            Quantity = 3
                        },
                        new
                        {
                            ItemID = 20,
                            CartId = 10,
                            ProductID = 20,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("MovieStore_API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            OrderDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            OrderDate = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 3,
                            OrderDate = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            OrderId = 4,
                            OrderDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            OrderId = 5,
                            OrderDate = new DateTime(2023, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            OrderId = 6,
                            OrderDate = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 6
                        },
                        new
                        {
                            OrderId = 7,
                            OrderDate = new DateTime(2023, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 7
                        },
                        new
                        {
                            OrderId = 8,
                            OrderDate = new DateTime(2023, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 8
                        },
                        new
                        {
                            OrderId = 9,
                            OrderDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 9
                        },
                        new
                        {
                            OrderId = 10,
                            OrderDate = new DateTime(2023, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 10
                        });
                });

            modelBuilder.Entity("MovieStore_API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Action",
                            Description = "A thief who enters the dreams of others to steal secrets from their subconscious.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/7/7f/Inception_ver3.jpg",
                            Name = "Inception",
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Action",
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/8/8a/Dark_Knight.jpg",
                            Name = "The Dark Knight",
                            Price = 11.99m
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Drama",
                            Description = "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg",
                            Name = "Fight Club",
                            Price = 10.99m
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Crime",
                            Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg",
                            Name = "Pulp Fiction",
                            Price = 11.99m
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Drama",
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg",
                            Name = "The Shawshank Redemption",
                            Price = 10.99m
                        },
                        new
                        {
                            ProductId = 6,
                            Category = "Drama",
                            Description = "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg",
                            Name = "Forrest Gump",
                            Price = 8.99m
                        },
                        new
                        {
                            ProductId = 7,
                            Category = "Crime",
                            Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
                            Name = "The Godfather",
                            Price = 13.99m
                        },
                        new
                        {
                            ProductId = 8,
                            Category = "Sci-Fi",
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg",
                            Name = "The Matrix",
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 9,
                            Category = "Crime",
                            Description = "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/7/7b/Goodfellas.jpg",
                            Name = "Goodfellas",
                            Price = 11.99m
                        },
                        new
                        {
                            ProductId = 10,
                            Category = "Fantasy",
                            Description = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/9/9d/Lord_of_the_Rings_-_The_Return_of_the_King.jpg",
                            Name = "The Lord of the Rings: The Return of the King",
                            Price = 14.99m
                        },
                        new
                        {
                            ProductId = 11,
                            Category = "Fantasy",
                            Description = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/9/9d/Lord_of_the_Rings_-_The_Fellowship_of_the_Ring_%282001%29_theatrical_poster.jpg",
                            Name = "The Lord of the Rings: The Fellowship of the Ring",
                            Price = 13.99m
                        },
                        new
                        {
                            ProductId = 12,
                            Category = "Fantasy",
                            Description = "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/a/ad/Lord_of_the_Rings_-_The_Two_Towers.jpg",
                            Name = "The Lord of the Rings: The Two Towers",
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 13,
                            Category = "Crime",
                            Description = "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/0/03/Godfather_part_ii.jpg",
                            Name = "The Godfather: Part II",
                            Price = 13.99m
                        },
                        new
                        {
                            ProductId = 14,
                            Category = "Drama",
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg",
                            Name = "The Shawshank Redemption",
                            Price = 10.99m
                        },
                        new
                        {
                            ProductId = 15,
                            Category = "Action",
                            Description = "Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/8/83/Dark_knight_rises_poster.jpg",
                            Name = "The Dark Knight Rises",
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 16,
                            Category = "Drama",
                            Description = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg",
                            Name = "Schindler's List",
                            Price = 11.99m
                        },
                        new
                        {
                            ProductId = 17,
                            Category = "Fantasy",
                            Description = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/9/9d/Lord_of_the_Rings_-_The_Fellowship_of_the_Ring_%282001%29_theatrical_poster.jpg",
                            Name = "The Lord of the Rings: The Fellowship of the Ring",
                            Price = 13.99m
                        },
                        new
                        {
                            ProductId = 18,
                            Category = "Fantasy",
                            Description = "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/a/ad/Lord_of_the_Rings_-_The_Two_Towers.jpg",
                            Name = "The Lord of the Rings: The Two Towers",
                            Price = 12.99m
                        },
                        new
                        {
                            ProductId = 19,
                            Category = "Fantasy",
                            Description = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/9/9d/Lord_of_the_Rings_-_The_Return_of_the_King.jpg",
                            Name = "The Lord of the Rings: The Return of the King",
                            Price = 14.99m
                        },
                        new
                        {
                            ProductId = 20,
                            Category = "Drama",
                            Description = "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg",
                            Name = "Forrest Gump",
                            Price = 8.99m
                        });
                });

            modelBuilder.Entity("MovieStore_API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin1234@gmail.com",
                            Password = "1234",
                            ProfilePicture = "profile1.jpg",
                            UserType = "Admin",
                            Username = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "john.doe@gmail.com",
                            Password = "password123",
                            ProfilePicture = "profile1.jpg",
                            UserType = "Customer",
                            Username = "JohnDoe"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "jane.smith@gmail.com",
                            Password = "password456",
                            ProfilePicture = "profile2.jpg",
                            UserType = "Customer",
                            Username = "JaneSmith"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "michael.scott@gmail.com",
                            Password = "ilovepaper",
                            ProfilePicture = "profile3.jpg",
                            UserType = "Customer",
                            Username = "MichaelScott"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "emily.johnson@yahoo.com",
                            Password = "securepass",
                            ProfilePicture = "profile4.jpg",
                            UserType = "Customer",
                            Username = "EmilyJohnson"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "david.lee@outlook.com",
                            Password = "david123",
                            ProfilePicture = "profile5.jpg",
                            UserType = "Customer",
                            Username = "DavidLee"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "michelle.williams@protonmail.com",
                            Password = "michelle",
                            ProfilePicture = "profile6.jpg",
                            UserType = "Customer",
                            Username = "MichelleWilliams"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "alex.turner@gmail.com",
                            Password = "arctic123",
                            ProfilePicture = "profile7.jpg",
                            UserType = "Customer",
                            Username = "AlexTurner"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "emma.watson@yahoo.com",
                            Password = "hermione",
                            ProfilePicture = "profile8.jpg",
                            UserType = "Customer",
                            Username = "EmmaWatson"
                        },
                        new
                        {
                            UserId = 10,
                            Email = "chris.hemsworth@outlook.com",
                            Password = "thorlove",
                            ProfilePicture = "profile9.jpg",
                            UserType = "Customer",
                            Username = "ChrisHemsworth"
                        });
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<int>("OrdersOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.HasKey("OrdersOrderId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("OrderProduct", (string)null);
                });

            modelBuilder.Entity("CartProduct", b =>
                {
                    b.HasOne("MovieStore_API.Models.Cart", null)
                        .WithMany()
                        .HasForeignKey("CartsCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieStore_API.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieStore_API.Models.Cart", b =>
                {
                    b.HasOne("MovieStore_API.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("MovieStore_API.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieStore_API.Models.Item", b =>
                {
                    b.HasOne("MovieStore_API.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieStore_API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieStore_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MovieStore_API.Models.Order", b =>
                {
                    b.HasOne("MovieStore_API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("MovieStore_API.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieStore_API.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieStore_API.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MovieStore_API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MovieStore_API.Models.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
